name: substrate_metadata
description: substrate_metadata description
version: 1.0.0
homepage: https://github.com/rankanizer/polkadart

# TODO: Remove this when polkadart_scale_codec is published
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  build_runner: ^2.2.1 # BSD-3-Clause
  cached: ^1.2.2 # MIT
  cached_annotation: ^1.2.0 # MIT
  cryptography: ^2.0.5 # Apache-2.0
  equatable: ^2.0.5 # MIT
  json_schema2: ^2.0.2+9 # MIT
  
  # TODO: Remove this when polkadart_scale_codec is published
  # and change to generic way of getting repository from pub.dev
  polkadart_scale_codec:
    git:
      url: https://github.com/rankanizer/polkadart.git
      ref: feature/polkadart_scale_codec
      path: packages/polkadart_scale_codec
  
  utility: ^1.0.3 # MIT
  weak_map: ^2.1.0 # BSD-2-Clause

dev_dependencies:
  path: ^1.8.2 # BSD-3-Clause
  lints: ^2.0.0
  test: ^1.16.0
